### ISSUE TITLE
When using script as git hook, shell script cannot find python script

### ISSUE THREAD

**Issue by s-waite** [markuswt/gpt-commit#10]
## Expected Behavior
The shell script `prepare-commit-msg` invokes the python script if the commit message is empty

## Current Behavior
```sh
.git/hooks/prepare-commit-msg: line 5: ./gpt-commit.py: No such file or directory
```

## Possible Solution
Edit the shell script to get the full path of the "gpt-commit.py" file and use that to run the python script
```sh
SCRIPT_DIR=$(dirname "$0")
"${SCRIPT_DIR}/gpt-commit.py" --print-message > "$1"
```

## Steps to Reproduce

1. Clone repo and copy `gpt-commit.py` and `prepare-commit-msg` into the `.git/hooks` dir of a project
2. In the project root, run `git commit`

## Context (Environment)
I think the path to the python script can't be resolved when the hook runs when you're in a different directory than the python script.

Using MacOS Ventura 13.2 on MacBook Pro M1 2020

**Comment by markuswt** [comment]
Thank you, fixed it
