### ISSUE TITLE
HTTPError: 429

### ISSUE THREAD

**Issue by idanyelin** [markuswt/gpt-commit#3]
Made a relatively minor change in two files (the entire repository is ~50 text files). 
Got this error: 

Traceback (most recent call last):
  File "gpt-commit/gpt-commit.py", line 82, in <module>
    commit_message = generate_commit_message(summarize_diff(diff))
  File "gpt-commit/gpt-commit.py", line 35, in summarize_diff
    return complete(DIFF_PROMPT + "\n\n" + diff + "\n\n")
  File "gpt-commit/gpt-commit.py", line 28, in complete
    response.raise_for_status()
  File "/XXX/.conda/envs/daily1/lib/python3.10/site-packages/requests/models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 429 Client Error: Too Many Requests for url: https://api.openai.com/v1/completions

Any idea what could be causing this?

**Comment by markuswt** [comment]
Seems like you're getting rate limited. For two small changes there should only be two API calls.

Have you been using `gpt-commit` a lot? Do you have any other programs using the OpenAI API?

**Comment by idanyelin** [comment]
That's what I thought. 
Haven't been using any other programs using the OpenAI API. 
Also, I got this error the first time I used gpt-commit. That is, unless you count a couple of times when it was used with an incorrect key and returned a different error (401)). 
I now also tried it once on a 'fresh' git in a new test directory with a single one-line file. It still returns the same error. :(

**Comment by markuswt** [comment]
That's strange indeed. Could you double-check if you have exceeded your [free trial credits](https://platform.openai.com/account/usage)?

**Comment by idanyelin** [comment]
Oh...
You're right. I missed it.
Sorry for the trouble.
