### ISSUE TITLE
OpenAI rate limit error

### ISSUE THREAD

**Issue by ayoahha** [markuswt/gpt-commit#7]
Hi there
I encounter this error when trying to call gpt-commit.py :
```
openai.error.RateLimitError: The server had an error while processing your request. Sorry about that!
```
I am on linux, and i configured globally the local git repo that i cloned on my machine, so that i can call from anywhere the command...
**Is there any ratelimit on openAI ?**
**Or is there any issue with the code ?**
Many thanks and congrats for your job ;)

**Comment by markuswt** [comment]
Most likely you're retting rate limited by OpenAI. See also #3.

Could you if you have exceeded your [free trial credits](https://platform.openai.com/account/usage)?

**Comment by ayoahha** [comment]
Strange, cause i do not use many times

**Comment by ayoahha** [comment]
OK, it seems it is now working well on others repos. I did not do anything!
Maybe it is my repository.
Thanks anyway
